### ISSUE TITLE
can you share the android apk file? thanks

### ISSUE THREAD

**Issue by hyaihjq** [WZTENG/YOLOv5_NCNN#1]

**Comment by WZTENG** [comment]
Apk file is very big(80MB), let me send you email.
An error occurred during the compilation of APK. The minimum version was modified.
minSdkVersion 24 -> minSdkVersion 26

**Comment by hyaihjq** [comment]
> ===[ translation ]===
> Apk file is very big(80MB), let me send you email.
> An error occurred during the compilation of APK. The minimum version was modified.
> minSdkVersion 24 -> minSdkVersion 26

my email is 1454671689@qq.com， thanks for your best work
