### ISSUE TITLE
大佬可以单独写个ncnn的yolov5代码么？不是android和ios的，谢谢！！！

### ISSUE THREAD

**Issue by hyaihjq** [WZTENG/YOLOv5_NCNN#12]

**Comment by WZTENG** [comment]
直接参考官方代码，v5跟v4差不多
https://github.com/Tencent/ncnn/tree/master/examples

**Comment by hyaihjq** [comment]
> 直接参考官方代码，v5跟v4差不多
> https://github.com/Tencent/ncnn/tree/master/examples

ok，谢谢

**Comment by sporterman** [comment]
@hyaihjq 有写出来吗
