### ISSUE TITLE
请教一下作者，YOLOv5中，将NMS放进模型里是否可行

### ISSUE THREAD

**Issue by Xiaokeai18** [WZTENG/YOLOv5_NCNN#15]
这个repo用手写的for循环实现NMS，效率有些低，请问一下，在把NMS放进模型里面，然后再转换为NCNN，这种方法是否可行？

**Comment by WZTENG** [comment]
主要差距是yolov3中YOLOLayer层与yolov5中Detect层，在导出时区分有后处理与没有后处理。
