### ISSUE TITLE
yolov5.param问题

### ISSUE THREAD

**Issue by Liangdacai** [WZTENG/YOLOv5_NCNN#19]
你好，我自己训练，通过官方的export导出onnx，通过onnxsim简化，有700多层，你的只有300多层，可以指点下吗？

**Comment by WZTENG** [comment]
用的v1版本。不确定现在是不是v5更新了模型。

**Comment by Single430** [comment]
我觉得是没有什么影响的，只要你将.param中的输出层对应的数字找到就行，我跑了好两个版本，最后.param都不一样，结果都是对的

```python
//        {"394",32,{{116,90},{156,198},{373,326}}},
//        {"375",16,{{30,61},{62,45},{59,119}}},
        // yolov5s
//        {"404",32,{{116,90},{156,198},{373,326}}},
//        {"384",16,{{30,61},{62,45},{59,119}}},

        // yolov5s
//        {"761",32,{{116,90},{156,198},{373,326}}},
//        {"741",16,{{30,61},{62,45},{59,119}}},
```

**Comment by Liangdacai** [comment]
> 我觉得是没有什么影响的，只要你将.param中的输出层对应的数字找到就行，我跑了好两个版本，最后.param都不一样，结果都是对的
> 
> ```python
> //        {"394",32,{{116,90},{156,198},{373,326}}},
> //        {"375",16,{{30,61},{62,45},{59,119}}},
>         // yolov5s
> //        {"404",32,{{116,90},{156,198},{373,326}}},
> //        {"384",16,{{30,61},{62,45},{59,119}}},
> 
>         // yolov5s
> //        {"761",32,{{116,90},{156,198},{373,326}}},
> //        {"741",16,{{30,61},{62,45},{59,119}}},
> ```
> 
> 我还试了yovol5m，也是可以的
> 
> ```python
>         // yolov5m
>         {"1032",32,{{116,90},{156,198},{373,326}}},
>         {"1012",16,{{30,61},{62,45},{59,119}}},
>         {"output",8,{{10,13},{16,30},{33,23}}},
> ```

**Comment by Liangdacai** [comment]
是的，起初我生成出来的index比较多（相对于博主），以为博主做了压缩蒸馏等方法，新版v5里面用了hardwish激活函数，ncnn不支持，转成了很多小模块替代，导致index增多。谢谢你们的解惑。
