### ISSUE TITLE
你好，在build的时候报以下错误。。。

### ISSUE THREAD

**Issue by zlszhonglongshen** [WZTENG/YOLOv5_NCNN#9]
Build command failed.
Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C C:\Users\Administrator\Desktop\ncnn\YOLOv5_NCNN-master\android_YOLOV5_NCNN\app\.cxx\cmake\debug\x86 yolov5}
ninja: Entering directory `C:\Users\Administrator\Desktop\ncnn\YOLOv5_NCNN-master\android_YOLOV5_NCNN\app\.cxx\cmake\debug\x86'

ninja: error: 'C:/Users/Administrator/Desktop/ncnn/YOLOv5_NCNN-master/android_YOLOV5_NCNN/app/src/main/cpp/opencv/x86/libopencv_java4.so', needed by 'C:/Users/Administrator/Desktop/ncnn/YOLOv5_NCNN-master/android_YOLOV5_NCNN/app/build/intermediates/cmake/debug/obj/x86/libyolov5.so', missing and no known rule to make it

**Comment by WZTENG** [comment]
opencv不包含x86/x86_64的库，太大了没有放进工程。所以默认只支持armeabi-v7a与arm64-v8a

**Comment by zlszhonglongshen** [comment]
> opencv不包含x86/x86_64的库，太大了没有放进工程。所以默认只支持armeabi-v7a与arm64-v8a

大佬 该怎么搞呀  刚开始接触 Android studio

**Comment by WZTENG** [comment]
更新到最新版本再试试，，其它的我也不懂了，，多去网上找找有没有解决办法。

**Comment by zlszhonglongshen** [comment]
> 更新到最新版本再试试，，其它的我也不懂了，，多去网上找找有没有解决办法。

![image](https://user-images.githubusercontent.com/9023908/90725478-ceefb380-e2f2-11ea-81d8-6a0d8095082a.png)
大佬 这个是啥问题呀？

**Comment by WZTENG** [comment]
电脑模拟器是x86的，界面也需要摄像头的，所以用真机测。

**Comment by Dreamskya** [comment]
@zlszhonglongshen 在studio左下角的地方，有个Build的，切换armv7架构进行运行。

**Comment by WZTENG** [comment]
现在这么nb的嘛，一直都用真机来搞的。。。老了，跟不上年轻人了

**Comment by zlszhonglongshen** [comment]
> 现在这么nb的嘛，一直都用真机来搞的。。。老了，跟不上年轻人了

我先试试呀，我也是第一次搞这个，就直接拿你的来测了，并不知道怎么在真机搞的

**Comment by zlszhonglongshen** [comment]
> > 现在这么nb的嘛，一直都用真机来搞的。。。老了，跟不上年轻人了
> 
> 我先试试呀，我也是第一次搞这个，就直接拿你的来测了，并不知道怎么在真机搞的

Cannot build selected target ABI: x86, no suitable splits configured: arm64-v8a;

**Comment by zlszhonglongshen** [comment]
> > 现在这么nb的嘛，一直都用真机来搞的。。。老了，跟不上年轻人了
> 
> 我先试试呀，我也是第一次搞这个，就直接拿你的来测了，并不知道怎么在真机搞的

![image](https://user-images.githubusercontent.com/9023908/90731136-df585c00-e2fb-11ea-8b78-c22b6cfc0d2b.png)

**Comment by zlszhonglongshen** [comment]
> > > 现在这么nb的嘛，一直都用真机来搞的。。。老了，跟不上年轻人了
> > 
> > 
> > 我先试试呀，我也是第一次搞这个，就直接拿你的来测了，并不知道怎么在真机搞的
> 
> ![image](https://user-images.githubusercontent.com/9023908/90731136-df585c00-e2fb-11ea-8b78-c22b6cfc0d2b.png)

大佬 不然你把你的X86 和 x64 发给我？谢谢了

**Comment by WZTENG** [comment]
首先工程中没有opencv x86/x64的so文件，需要自己去下载，然后编译时只保留armeabi-v7a/arm64-v8a的文件。
![image](https://user-images.githubusercontent.com/19603468/90731730-a4a2f380-e2fc-11ea-9ff4-af57f8b2d54d.png)

**Comment by zlszhonglongshen** [comment]
> 首先工程中没有opencv x86/x64的so文件，需要自己去下载，然后编译时只保留armeabi-v7a/arm64-v8a的文件。
> ![image](https://user-images.githubusercontent.com/19603468/90731730-a4a2f380-e2fc-11ea-9ff4-af57f8b2d54d.png)

![image](https://user-images.githubusercontent.com/9023908/90843100-77555480-e393-11ea-987f-267d0fc67438.png)
大佬 这些文件 为什么都是0kb 呀 能不能打包 发一个百度链接？谢谢啦

**Comment by zlszhonglongshen** [comment]
> > 首先工程中没有opencv x86/x64的so文件，需要自己去下载，然后编译时只保留armeabi-v7a/arm64-v8a的文件。
> > ![image](https://user-images.githubusercontent.com/19603468/90731730-a4a2f380-e2fc-11ea-9ff4-af57f8b2d54d.png)
> 
> ![image](https://user-images.githubusercontent.com/9023908/90843100-77555480-e393-11ea-987f-267d0fc67438.png)
> 大佬 这些文件 为什么都是0kb 呀 能不能打包 发一个百度链接？谢谢啦

1366143083@qq.com

**Comment by WZTENG** [comment]
https://github.com/Tencent/ncnn/releases/tag/20200727
下载ncnn-android-lib.zip解压到ncnn
下载ncnn-android-vulkan-lib.zip解压到ncnnvulkan

**Comment by WZTENG** [comment]
opencv下载安卓的
https://opencv.org/releases/

**Comment by zlszhonglongshen** [comment]
> opencv下载安卓的
> https://opencv.org/releases/

感谢大大，搞通啦。谢谢耐心指导呀
