### ISSUE TITLE
目前移植自己训练的yolo_tiny模型是否可行

### ISSUE THREAD

**Issue by ChangAnCN** [WZTENG/YOLOv5_NCNN#96]
已通过yolov5s_custom_layer成功运行，但受限于目标设备的性能，和项目对流畅性的要求，需要移植更精简的模型。
目前对该框架还是一知半解，是否只需要更换parm和bin 然后修改对应的.h文件即可？

十分感谢！！

**Comment by cmdbug** [comment]
看官方ncnn的examples啊，api很简单的
